# Generated by Django 5.0.6 on 2026-05-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=50)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('office', 'Office'), ('warehouse', 'Warehouse')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_row', models.JSONField(default=dict)),
                ('ingestion_status', models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='clean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_code', models.CharField(blank=True, max_length=100, null=True)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('parsed_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_record_id', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('original_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('original_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('scope', models.CharField(blank=True, max_length=50, null=True)),
                ('emission_factor', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('source_file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_row', models.JSONField(default=dict)),
                ('ingestion_status', models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='clean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculated_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('distance_source', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_row', models.JSONField(default=dict)),
                ('ingestion_status', models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='clean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_consumption', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
