# Generated by Django 5.0.6 on 2026-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilityrecord',
            old_name='account_number',
            new_name='parsed_unit',
        ),
        migrations.RenameField(
            model_name='utilityrecord',
            old_name='provider_name',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='calculated_distance_km',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='distance_source',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='raw_distance_km',
        ),
        migrations.RemoveField(
            model_name='utilityrecord',
            name='meter_id',
        ),
        migrations.RemoveField(
            model_name='utilityrecord',
            name='normalized_consumption',
        ),
        migrations.RemoveField(
            model_name='utilityrecord',
            name='normalized_unit',
        ),
        migrations.RemoveField(
            model_name='utilityrecord',
            name='raw_consumption',
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='traveler_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilityrecord',
            name='parsed_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='utilityrecord',
            name='raw_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilityrecord',
            name='utility_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('office', 'Office'), ('warehouse', 'Warehouse')], default='manufacturing', max_length=50),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='travel_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilityrecord',
            name='raw_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
