# Generated by Django 5.0.6 on 2026-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_account_number_utilityrecord_parsed_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelrecord',
            old_name='distance_km',
            new_name='calculated_distance_km',
        ),
        migrations.RenameField(
            model_name='travelrecord',
            old_name='traveler_name',
            new_name='employee_id',
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='distance_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='error_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='hotel_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='raw_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='travel_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='travel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
