# Generated by Django 5.0.6 on 2026-05-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_distance_km_travelrecord_calculated_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrecord',
            name='error_notes',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='hotel_city',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='travel_class',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='travel_date',
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='calculated_distance_km',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='distance_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='employee_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='origin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='raw_distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='travel_type',
            field=models.CharField(max_length=100),
        ),
    ]
